project:
    type: website

website:
    title: "Sage Shaw"
    open-graph: true
    navbar:
        left:
            - href: about.qmd
              text: About
            - href: publications.qmd
              text: Publications
            - href: resume.qmd
              text: Resume
            - href: software.qmd
              text: Software
        tools:
            - icon: envelope
              href: mailto:sage.b.shaw@gmail.com
              target: blank
            - icon: github
              href: https://www.github.com/shawsa
            - icon: linkedin
              href: https://www.linkedin.com/in/sage-shaw-a0919577/

format:
    html:
        theme:
            - minty
        css: styles.css
        toc: true
